### ISSUE TITLE
[META] - Miscs

### ISSUE THREAD

**Issue by alanlanglois** [telabotanica/smartflore-flutter#42]
- [ ] App icon
- [ ] App SplashScreen
- [ ] Localization
- [ ] Theme manager
- [ ] Transfert Android App
- [ ] Create iOS App
- [ ] Testting channel io / Android
- [ ] Auto deploy
