### ISSUE TITLE
[Meta] - Settings

### ISSUE THREAD

**Issue by alanlanglois** [telabotanica/smartflore-flutter#84]
- [ ] [Settings] - UI Integration
- [ ] [Settings] - Add About / Terms of use / Credits and Webviews
- [ ] [Settings] - Add Localization Options
- [ ] [Settings] - Login / Logout
